### ISSUE TITLE
Potential ambiguity in bot:Zone rdfs:description

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#17]
I was wondering if their might be some ambiguity of the concept bot:Zone

>  rdfs:comment    "An area or stretch of land

From our discussions and the subclasses drawn from Zone I was wandering if only mentioning Area and stretch of land in the description might be misleading as Zone describes things which have a volume.

**Comment by MadsHolten** [comment]
Hi Georg. Thanks for raising the issue. In the future, it would be great if you could also suggest a solution.

Area is more like "område" in danish or "Gebiet" as I think it would translate in german. I am happy to discuss an alternative definition of a zone.

**Comment by pipauwel** [comment]
A defined area with spatial 3D volume that groups spaces and has a particular characteristic, purpose, or use, or subject to particular restrictions. A bot:Zone can contain other bot:Zones defined by the relation bot:containsZone, and it can be connected to other bot:Zones defined by the relation bot:adjacentZone. BRICK:HVAC_Zone would then be a subClass of bot:Zone, for example.

**Comment by pipauwel** [comment]
Alternative options for the definition of zone:
-  "A defined spatial 3D volume that can represent a site, a building, a storey or a space. It can also be used to group other zones, or to define subdivisions of zones"
- "A defined spatial 3D volume that can represent a site, a building, a storey or a space or any other spatial feature of interest. A zone can contain sub zones making it possible to do grouping or subdivision of existing zones."

=> need to decide on a final definition

**Comment by stickxxx** [comment]
Why not use the ISO definition for "zone" - ISO 18523-2:2018, 3.1.3 defines it as
"part of a building consisting of (part of) one or more spaces with assumed uniform properties related to a specific service or service component, or (in absence of a service) assumed uniform indoor environmental conditions"
ISO 18523-2:2018 is for "Energy performance of buildings -- Schedule and condition of building, zone and space usage for energy calculation"

**Comment by GeorgFerdinandSchneider** [comment]
Hi all!

thanks @stickxxx for pointing to the ISO definition. I think this ideally reflects the ambiguity of bot:Zone

> "part of a building consisting of (part of) one or more spaces with assumed uniform properties related to a specific service or service component, or (in absence of a service) assumed uniform indoor environmental conditions"

The ISO defines zone as part of a building. A `bot:Zone` can acutally be a bot:Building. Moreover a `bot:Zone` which is a `bot:Site` can have parts which are buildings. This contradicts the ISO definition in my opinion.

With respect to the definitions given by Pieter above I would like to suggest the following adapted:

> "An abstract concept that can represent a site, a building, a storey or a space or any other two or threedimensional feature of interest. A zone can contain sub zones making it possible to do grouping or subdivision of existing zones."

Best

Georg

**Comment by MadsHolten** [comment]
The ISO definition describes zones in the context of energy performance and BOT uses the term in a wider meaning. But as Georg points out it is not so different from the BOT concept and the two of them are quite easy to align. I think there should be an indoor climate and energy (ICE) ontology at one point and it would make a lot of sense if it defines ice:HeatingZone, ice:CoolingZone and ice:VentilationZone / ice:VentingZone as subClasses of bot:Zone.

Often when I describe the main classes of BOT I say that it describes spatial and tangible elements (and interfaces) at top level. I have been thinking that maybe bot:spatialElement would be a better term, but then on the other hand 1) it is a little late to change one of the main terms as we already are seeing implementations and 2) we would probably have the same kind of discussions about bot:spatialElement.

Our main focus now should be on making sharp, unambiguous descriptions so that there is no reason to question what is meant.

That being said, I like the final description of yours, Georg.

**Comment by stickxxx** [comment]
I'm also ok with the definition of Georg - it's just the "abstract concept" part that bothers me a bit.
Still, with regard to what @MadsHolten says (e.g. bot:SpatialElement), why not consider bot:Zone as a "spatial division" ? 
The definition of Georg becomes: "A spatial division can represent any 2- or 3-d feature of interest (e.g. site, building, storey, space)."

**Comment by MadsHolten** [comment]
I am not sure it can be 2D but in principle, I am fine with allowing it to be either 2- or 3D. This would entail that you do not necessarily have to define the height and depth of a site and that it is okay to have a 2D geometrical definition of some zone. I have used this in one of my implementations: <zone> props:2dBoundary "POLYGON(x y, ...)"^^geo:wktLiteral.

**Comment by mathib** [comment]
I think we should stick with the 3D definition. A site is also 3D, as it is always (?) limited in height above and depth below the ground surface. Height is limited by laws about spatial planning and depth is also limited e.g. because of infrastructure below the building (runnels for roads, subway, etc.). When you buy a piece of land, you only own it until a certain amount of depth and height, right? This makes that the concept of a zone is always 3D, but the dimensions don't have to be expressed always explicitly. In this case, Mads can use props:2dBoundary without contradicting to the definition in BOT (heigth and depth is just undefined = OWA). In fact, you can also define a zone without any geometry related properties.

A feature of interest is too generic, as it can also be, let's say a 'chair' and thus a bot:Element.

I would opt for the following definition, as a combination of the ones of Georg and Ana:

> A spatial 3D division that can represent a site, a building, a storey or a space. An instance of bot:Zone can contain sub zones making it possible to group or subdivide other zones.

**Comment by maximelefrancois86** [comment]
With this last one, one could think a zone must be either a site, a building, a storey, or a space. 

Also, the definition mentions zones can contain zones, but not the fact that zones can be adjacent to other zones, not zones can have elements.

What about:

> A spatial 3D division. Sub-classes of bot:Zones include bot:Site, bot:Building, bot:Storey, or bot:Space. An instance of bot:Zone can contain other bot:Zones, making it possible to group or subdivide zones. An instance of bot:Zone can be adjacent to other bot:Zones. Finally, an instance of bot:Zone can have bot:Elements, which are either contained in, or adjacent to, the bot:Zone.

**Comment by maximelefrancois86** [comment]
(should it be connex also?)

**Comment by stickxxx** [comment]
I'm okay with your version Maxime. 
I'd just slightly chnage your last sentence: "bot:Zone can instantiate two relations to bot:Element. which are either contained in (bot:...), or adjacent to it (bot:...)."
I'd also remove the plural from "bot:Zones" in your second sentence ;)

**Comment by MadsHolten** [comment]
I think Maxime is referring to the new super-property of bot:containsElement and bot:adjacentElement -> bot:hasElement.

**Comment by MadsHolten** [comment]
Can we all agree on this?

> A spatial 3D division. Sub-classes of bot:Zones include bot:Site, bot:Building, bot:Storey, or bot:Space. An instance of bot:Zone can contain other bot:Zone instances, making it possible to group or subdivide zones. An instance of bot:Zone can be adjacent to other bot:Zone instances. Finally, a bot:Zone can instantiate two relations to bot:Element, which are either contained in (bot:containsElement), or adjacent to it (bot:adjacentElement).

I like this since we do not want people to explicitly state the bot:hasElement. I also think we should consider adding this to the description of bot:hasElement

> Links a Zone to an Element that is either contained in or adjacent to, the Zone. The intended use of this relationship is not to be stated explicitly, but to be inferred from its sub-properties. It will, for example, allow one to query for all the doors of a building given that they have an adjacency to spaces of the building.

Can we agree on these or at least one of them?

**Comment by stickxxx** [comment]
All good for me, perhaps for the sake of coherence, I'd add "bot:Zone" and "bot:Element" in your definition of bot:hasElement.

**Comment by pipauwel** [comment]
?Sounds good, Mads. Agree.




________________________________
Van: stickxxx <notifications@github.com>
Verzonden: donderdag 14 juni 2018 17:52
Aan: w3c-lbd-cg/bot
CC: Pieter Pauwels; State change
Onderwerp: Re: [w3c-lbd-cg/bot] Potential ambiguity in bot:Zone rdfs:description (#17)


All good for me, perhaps for the sake of coherence, I'd add "bot:Zone" and "bot:Element" in your definition of bot:Element.

-

**Comment by MadsHolten** [comment]
Has now been updated. Only danish and english descriptions have been revised to the new definition.

**Comment by maximelefrancois86** [comment]
can we close the issue now?
