### ISSUE TITLE
Cardinality restriction on interfaces

### ISSUE THREAD

**Issue by MadsHolten** [w3c-lbd-cg/bot#20]
Currently bot:interfaceOf has a cardinality restriction of 2, which might be a problem.

For quantifying for instance a heat transmission area, it is correct that the cardinality will always be 2 (ie. the wall and the space), but for modelling linear transmission losses, one would need to specify the cold bridge as an interface between for instance two walls and a space or a window, a wall and a space.

**Comment by pipauwel** [comment]
Then I would suggest to simply leave out the cardinality restrictions. Are they used for a specific purpose?

**Comment by MadsHolten** [comment]
An interface must be an interfaceOf at least two things in order to exist. I also agree with you that stuff like this should be taken care of by the application rather than by adding restrictions and the main reason why it is in there is because reviewer's of our work inquire them.

**Comment by pipauwel** [comment]
but for modelling linear transmission losses, one would need to specify the cold bridge as an interface between for instance two walls and a space or a window, a wall and a space.


=> This is a relevant point. Are there other exceptions? I think that linear transmission losses are quite a bit different from planar transmission losses. What about modelling them differently then (two distinct classes and properties - e.g. edgeOf)? In that case, the "interfaceOf" can keep the cardinality restriction of 2, and the edgeOf can exist without cardinality restrictions. Would an edgeOf property need a direction (outside to inside)?




________________________________
Van: Mads Holten Rasmussen <notifications@github.com>
Verzonden: vrijdag 25 mei 2018 22:32
Aan: w3c-lbd-cg/bot
CC: Pieter Pauwels; Comment
Onderwerp: Re: [w3c-lbd-cg/bot] Cardinality restriction on interfaces (#20)


An interface must be an interfaceOf at least two things in order to exist. I also agree with you that stuff like this should be taken care of by the application rather than by adding restrictions and the main reason why it is in there is because reviewer's of our work inquire them.

-

**Comment by MadsHolten** [comment]
We can also just make it a minimum restriction instead?

```
bot:Interface rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty bot:interfaceOf ;
    owl:minCardinality 2
] .
```

**Comment by mathib** [comment]
@MadsHolten : how do you model the interface between an outdoor wall and the outdoor air? Do you model the outdoor air as a separate zone? If this is the case, you can indeed make such a min restriction

**Comment by maximelefrancois86** [comment]
Hi,

my 2 cents:

MinCard 2 will make the ontology OWL Full -> no OWL reasoner will want to work with it

yes the outdoor air could be modeled as a separate zone

**Comment by MadsHolten** [comment]
Now defined as a minimum cardinality of 1. I thereby close this issue.
