### ISSUE TITLE
Definition of Zone and Space makes confusing the part of the physical world and its 3D spatial extent

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/bot#43]
Reporting here an email exchange I had with an senior researcher in the Semantic Web Community.

Zones, Buildings, Spaces, do have a spatial extent, but they should not be confused with their spatial extent. 

The current definitions of bot:Zone and bot:Space is confusing wrt to this aspect.

We have DP bot:hasSimple3DModel (resp. OP bot:has3DModel)  that link a zone to its 3D model encoded as a literal (resp. described using some dedicated ontology). This can be considered as the description of the spatial extent.

Aligning to Dolce:

- the bot:Zone would be a sub-class of dul:PhysicalObject (or dul:PhysicalPlace), 
- bot:has3DModel would be a sub-property of dul:hasRegion 
- the range of bot:has3DModel would also be dul:SpaceRegion

Zone is some kind of redefinition of anything that has a spatial extent. So in a sense a "SpatialThing" with the understanding that "thing" also includes the interior of a boundary, and the boundary itself may be virtual It's really \exists hasSpatialExtent.SpatialExtent.

The distinction between spatial extent and spatial thing is primordial.

Re-including part of the Dolce terms definitions for clarity, we came to the conclusion that the following revision of the definitions would be important:
 

> bot:Zone - A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent; Sub-classes of bot:Zone include bot:Site, bot:Building, bot:Storey, or bot:Space. An instance of bot:Zone can contain other bot:Zone instances, making it possible to group or subdivide zones. An instance of bot:Zone can be adjacent to other bot:Zone instances. Finally, a bot:Zone can instantiate two relations to bot:Element, which are either contained in (bot:containsElement). 

> bot:Space - A part of the physical world or a virtual world whose 3D spatial extent is bounded actually or theoretically, and provides for certain functions within the zone it is contained in.

**Comment by GeorgFerdinandSchneider** [comment]
Hi Max!

great you point this out. We should find a way to settle this.

Please see https://github.com/w3c-lbd-cg/bot/tree/AlignmentRevision  including the https://github.com/w3c-lbd-cg/bot/blob/AlignmentRevision/DULAlignment.ttl file with a proposal for an alignment based on your wording.

Best

Georg

**Comment by GeorgFerdinandSchneider** [comment]
Following the discussion today a new proposal to agree on:

```turtle
bot:Zone rdfs:subClassOf dul:PhysicalObject .
bot:Interface rdfs:subClassOf dul:PhysicalObject .

bot:Site rdfs:subClassOf dul:PhysicalPlace .

bot:Building rdfs:subClassOf dul:DesignedArtifact .
bot:Storey rdfs:subClassOf dul:DesignedArtifact .
bot:Space rdfs:subClassOf dul:DesignedArtifact .
bot:Element rdfs:subClassOf dul:DesignedArtifact .

bot:has3DModel rdfs:subPropertyOf dul:hasRegion .
bot:has3DModel rdfs:range dul:SpaceRegion .

bot:containsZone rdfs:subPropertyOf dul:hasPart .
bot:containsElement rdfs:subPropertyOf dul:hasPart .

bot:adjacentZone rdfs:subPropertyOf dul:hasCommonBoundary .
bot:adjacentElement rdfs:subPropertyOf dul:hasCommonBoundary .

bot:intersectsZone rdfs:subPropertyOf dul:overlaps .
```

**Comment by mathib** [comment]
Hi Maxime and Georg, 

I think this discussion is very important as many people are indeed confused by this. I think it is also related to the discussion around adding a zero point and orientation to a `bot:Site` (see also issue https://github.com/w3c-lbd-cg/bot/issues/41). The zero point is in this case rather a **_description of the spatial extent_** of the `bot:Site` (instead of the intended georeferencing), while a 2D polygon or a 3D geometry could be another description of the spatial extent of the same `bot:Site`. Georeferencing should probably be done by defining a georeference property connected to each individual **_description of the spatial extent_** (e.g. a linked 3D representation) of the `bot:Site` / `bot:Building` / ... I don't think an orientation property for georeferencing connected to the `bot:Site` is then still relevant as the point/polygon/3D model representing the site will be the thing that's georeferenced. 

Currently, there are three options for georeferencing of representations of spatial extent I can think of:
* one 3D point (georef of the local origin) and orientation => this approach misses scaling, so there should be a known unit of measurements that's applied in the local coordinate system.
* two 3D points (georef of the local origin + georef of another local point) => if the second point has a known (e.g. fixed) local coordinate, the geometry can also be scaled properly
* 4x4 transformation matrix (translation, rotation and scaling)

I'm in favor of updating the text definition of `bot:Zone`, `bot:Site`, `bot:Building`, `bot:Storey`, `bot:Space` and `bot:Element` (maybe also `bot:Interface`), as they each have a separate spatial extent (which can be either explicitly stated, e.g. via linking to a 3D geometry description, or implicitly stated, i.e. 'imagined' by the modeller).

Regarding the mapping to DUL, I did a review of the mappings and this seems OK for me. Good job, Georg! Maybe the following can be considered for the alignment (?):
`bot:intersectingElement rdfs:subPropertyOf dul:overlaps`
`bot:Interface rdfs:subClassOf dul:DesignedArtifact`
`bot:interfaceOf rdfs:subPropertyOf dul:hasCommonBoundary`

I think the best approach to continue is to sent a mail to the LBD mailinglist and/or discuss this during an upcoming LBD telco?
